# Generated by Django 4.1.3 on 2022-12-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Фильтрация',
                'verbose_name_plural': 'Фильтрации',
            },
        ),
    ]
